# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-12 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160220_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_pic',
            field=models.TextField(default=b'http://download.caiyun.feixin.10086.cn/storageWeb/servlet/GetFileByURLServlet?root=/mnt/wfs42&fileid=3Fe77a00d6bdfb5beccfb7295b71133b80.png&ct=1&type=1&code=BD26DD1BC55E13E64925B9D9BE78A129609F6FEBEBD4313F7635307B6FAE5FB8&exp=35026&account=MTM3NjE0MTgzMDc=&p=0&ui=0111Yvkc50I9&ci=0111Yvkc50I906420171210000034xxr&cn=python&oprChannel=10201200&dom=D992'),
        ),
    ]
